#!/bin/sh
exec /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome  --app="http://int.exoplatform.org/portal/intranet/chat/fluid" --user-data-dir="/Applications/eXo Chat.app/Contents/Profile" "$@"
